## SL Assignment 3

#### Name: pratiksha Dhembrae
#### PRN : 260240128031
--------------------
#### Name:vijay rajge
#### PRN : 260240128053

### Tips dataset exercises:

In [21]:
import pandas as pd
import seaborn as sns

In [88]:
#1. Load the tips dataset into a DataFrame.

df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [89]:
#2. Display the first 5 rows of the tips dataset.

df.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [90]:
#3. Show all column names in the tips dataset.

df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [25]:
#4. Find the average total_bill.
df['total_bill'].mean()

np.float64(19.78594262295082)

In [27]:
#5. Find the maximum tip given.
df['tip'].max()

np.float64(10.0)

In [30]:
#6. Filter all rows where total_bill is greater than 20.
df[df['total_bill'] > 20]

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
237       32.83  1.17    Male    Yes  Sat  Dinner     2
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2

[97 rows x 7 columns]

In [36]:
#7. Filter all rows where smoker is Yes.
df[df['smoker'] == 'Yes']

     total_bill   tip     sex smoker  day    time  size
56        38.01  3.00    Male    Yes  Sat  Dinner     4
58        11.24  1.76    Male    Yes  Sat  Dinner     2
60        20.29  3.21    Male    Yes  Sat  Dinner     2
61        13.81  2.00    Male    Yes  Sat  Dinner     2
62        11.02  1.98    Male    Yes  Sat  Dinner     2
..          ...   ...     ...    ...  ...     ...   ...
234       15.53  3.00    Male    Yes  Sat  Dinner     2
236       12.60  1.00    Male    Yes  Sat  Dinner     2
237       32.83  1.17    Male    Yes  Sat  Dinner     2
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2

[93 rows x 7 columns]

In [41]:
#8. Show only total_bill, tip, and day columns
df[['total_bill','tip','day']]

     total_bill   tip   day
0         16.99  1.01   Sun
1         10.34  1.66   Sun
2         21.01  3.50   Sun
3         23.68  3.31   Sun
4         24.59  3.61   Sun
..          ...   ...   ...
239       29.03  5.92   Sat
240       27.18  2.00   Sat
241       22.67  2.00   Sat
242       17.82  1.75   Sat
243       18.78  3.00  Thur

[244 rows x 3 columns]

In [85]:
#9. Find the average tip grouped by day.
df.groupby('day')['tip'].mean().reset_index()

    day       tip
0  Thur  2.771452
1   Fri  2.734737
2   Sat  2.993103
3   Sun  3.255132

In [84]:
#10. Find the average total_bill grouped by time.
df.groupby('time')['total_bill'].mean().reset_index()

     time  total_bill
0   Lunch   17.168676
1  Dinner   20.797159

In [44]:
#11. Count how many records belong to each day.
df['day'].count()

np.int64(244)

In [83]:
#12. Count how many smokers and non-smokers are present.
df['smoker'].value_counts().reset_index()

  smoker  count
0     No    151
1    Yes     93

In [82]:
#13. Find the total tip collected on each day.
df['tip'].sum()

AttributeError: 'numpy.float64' object has no attribute 'reset_index'

In [81]:
#14. Find the average tip for lunch and dinner separately.
df.groupby('time')['tip'].mean().reset_index()

     time       tip
0   Lunch  2.728088
1  Dinner  3.102670

In [61]:
#15. Create a new column tip_percent = (tip / total_bill) * 100.
df['tip_percent']= df['tip'] / df['total_bill'] * 100
df

     total_bill   tip     sex smoker   day    time  size  tip_percent
0         16.99  1.01  Female     No   Sun  Dinner     2     5.944673
1         10.34  1.66    Male     No   Sun  Dinner     3    16.054159
2         21.01  3.50    Male     No   Sun  Dinner     3    16.658734
3         23.68  3.31    Male     No   Sun  Dinner     2    13.978041
4         24.59  3.61  Female     No   Sun  Dinner     4    14.680765
..          ...   ...     ...    ...   ...     ...   ...          ...
239       29.03  5.92    Male     No   Sat  Dinner     3    20.392697
240       27.18  2.00  Female    Yes   Sat  Dinner     2     7.358352
241       22.67  2.00    Male    Yes   Sat  Dinner     2     8.822232
242       17.82  1.75    Male     No   Sat  Dinner     2     9.820426
243       18.78  3.00  Female     No  Thur  Dinner     2    15.974441

[244 rows x 8 columns]

In [80]:
#16. Find the row with the highest tip_percent.
df.loc[df['tip_percent'].idxmax()].reset_index()

         index        172
0   total_bill       7.25
1          tip       5.15
2          sex       Male
3       smoker        Yes
4          day        Sun
5         time     Dinner
6         size          2
7  tip_percent  71.034483

In [66]:
df[df['tip_percent'] == df['tip_percent'].max()]

     total_bill   tip   sex smoker  day    time  size  tip_percent
172        7.25  5.15  Male    Yes  Sun  Dinner     2    71.034483

In [79]:
#17. Find the average size of dining group by day.
df.groupby('day')['size'].mean().reset_index()

    day      size
0  Thur  2.451613
1   Fri  2.105263
2   Sat  2.517241
3   Sun  2.842105

In [71]:
#18. Sort the tips dataset by tip in descending order.
df.sort_values(by='tip', ascending=False)

     total_bill    tip     sex smoker   day    time  size  tip_percent
170       50.81  10.00    Male    Yes   Sat  Dinner     3    19.681165
212       48.33   9.00    Male     No   Sat  Dinner     4    18.621974
23        39.42   7.58    Male     No   Sat  Dinner     4    19.228818
59        48.27   6.73    Male     No   Sat  Dinner     4    13.942407
141       34.30   6.70    Male     No  Thur   Lunch     6    19.533528
..          ...    ...     ...    ...   ...     ...   ...          ...
0         16.99   1.01  Female     No   Sun  Dinner     2     5.944673
111        7.25   1.00  Female     No   Sat  Dinner     1    13.793103
92         5.75   1.00  Female    Yes   Fri  Dinner     2    17.391304
67         3.07   1.00  Female    Yes   Sat  Dinner     1    32.573290
236       12.60   1.00    Male    Yes   Sat  Dinner     2     7.936508

[244 rows x 8 columns]

In [74]:
#19. Filter records where size is greater than or equal to 4.
df[df['size'] >= 4].head()

    total_bill   tip     sex smoker  day    time  size  tip_percent
4        24.59  3.61  Female     No  Sun  Dinner     4    14.680765
5        25.29  4.71    Male     No  Sun  Dinner     4    18.623962
7        26.88  3.12    Male     No  Sun  Dinner     4    11.607143
11       35.26  5.00  Female     No  Sun  Dinner     4    14.180374
13       18.43  3.00    Male     No  Sun  Dinner     4    16.277808

In [78]:
#20. Find the average tip_percent for smokers vs non-smokers.
df.groupby('smoker')['tip_percent'].mean().reset_index()

  smoker  tip_percent
0    Yes    16.319604
1     No    15.932846